import type { Config } from 'tailwindcss'

export default {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",
                card: "var(--card)",
                'card-foreground': "var(--card-foreground)",
                popover: "var(--popover)",
                'popover-foreground': "var(--popover-foreground)",
                primary: "var(--primary)",
                'primary-foreground': "var(--primary-foreground)",
                secondary: "var(--secondary)",
                'secondary-foreground': "var(--secondary-foreground)",
                muted: "var(--muted)",
                'muted-foreground': "var(--muted-foreground)",
                accent: "var(--accent)",
                'accent-foreground': "var(--accent-foreground)",
                destructive: "var(--destructive)",
                'destructive-foreground': "var(--destructive-foreground)",
                border: "var(--border)",
                input: "var(--input)",
                ring: "var(--ring)",
                chart1: "var(--chart-1)",
                chart2: "var(--chart-2)",
                chart3: "var(--chart-3)",
                chart4: "var(--chart-4)",
                chart5: "var(--chart-5)",
                radius: "var(--radius)",
                sidebar: "var(--sidebar)",
                'sidebar-foreground': "var(--sidebar-foreground)",
                'sidebar-primary': "var(--sidebar-primary)",
                'sidebar-primary-foreground': "var(--sidebar-primary-foreground)",
                'sidebar-accent': "var(--sidebar-accent)",
                'sidebar-accent-foreground': "var(--sidebar-accent-foreground)",
                'sidebar-border': "var(--sidebar-border)",
                'sidebar-ring': "var(--sidebar-ring)",
            },
        },
    },
    plugins: [],
} satisfies Config